/**
 * @file express/src/lib/auth/sse-token.ts
 * @description JWT verification for SSE tokens (Express side).
 *
 * Tokens are generated by Next.js and verified here for SSE connections.
 */

import jwt from 'jsonwebtoken';

const JWT_SECRET = process.env.JWT_SECRET || 'fallback-secret-for-dev';

export interface SSETokenPayload {
  roomId: string;
  userId: number;
}

/**
 * Verify an SSE token from Next.js.
 *
 * @param token - The JWT token to verify
 * @returns The decoded payload, or null if invalid/expired
 */
export function verifySSEToken(token: string): SSETokenPayload | null {
  try {
    const payload = jwt.verify(token, JWT_SECRET) as {
      roomId: string;
      userId: number;
    };
    return {
      roomId: payload.roomId,
      userId: payload.userId,
    };
  } catch {
    return null;
  }
}
