/**
 * @file lib/auth/sse-token.ts
 * @description Short-lived JWT tokens for SSE connection verification.
 *
 * These tokens are generated by Next.js when a user joins a room and
 * verified by Express when establishing SSE connections.
 *
 * Token lifetime is intentionally short (60 seconds) since they're only
 * used to establish the initial SSE connection.
 *
 * @example
 * ```ts
 * // In Next.js API route
 * const token = await generateSSEToken(roomId, userId);
 *
 * // In Express SSE handler
 * const payload = await verifySSEToken(token);
 * if (payload) {
 *   // Valid - establish SSE connection
 * }
 * ```
 */

import { SignJWT, jwtVerify } from "jose";

// Use same secret as main auth - could be separate for production
const SSE_JWT_SECRET = new TextEncoder().encode(
  process.env.JWT_SECRET || "fallback-secret-for-dev"
);

/** Token expires in 60 seconds - enough to establish connection */
const SSE_TOKEN_TTL = 60;

export interface SSETokenPayload {
  roomId: string;
  userId: number;
}

/**
 * Generate a short-lived JWT for SSE connection.
 *
 * @param roomId - The room ID the user is connecting to
 * @param userId - The authenticated user's ID
 * @returns Signed JWT token
 */
export async function generateSSEToken(
  roomId: string,
  userId: number
): Promise<string> {
  return new SignJWT({ roomId, userId })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime(`${SSE_TOKEN_TTL}s`)
    .sign(SSE_JWT_SECRET);
}

/**
 * Verify an SSE token and extract its payload.
 *
 * @param token - The JWT token to verify
 * @returns The decoded payload, or null if invalid/expired
 */
export async function verifySSEToken(
  token: string
): Promise<SSETokenPayload | null> {
  try {
    const { payload } = await jwtVerify(token, SSE_JWT_SECRET);
    return {
      roomId: payload.roomId as string,
      userId: payload.userId as number,
    };
  } catch {
    return null;
  }
}
