import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link"
import { HeartbeatProvider } from "@/components/HeartbeatProvider"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeartbeatProvider>
          {/* <nav className="p-4 border-b flex gap-4 text-white">
            <Link href="/">Home</Link>
            <Link href="/chat">AI Assistant</Link>
            <Link href="/play">Tic-Tac-Toe</Link>
          </nav> */}
          {children}
        </HeartbeatProvider>
      </body>
    </html>
  )
}

